programs = [
  "1password",
  "1password-cli",
  "awscli",
  "borgbackup",
  "clustergit",
  "codebuild-agent",
  "dsutils",
  "git-secrets",
  "goenv",
  "golang",
  "granted",
  "mark",
  "openrefine",
  "packer",
  "pipx",
  "q",
  "rain",
  "rclone",
  "rocketchat",
  "s5cmd",
  "saml2aws",
  "shellcheck",
  "spotify",
  "sqlean",
  "typora",
  "vagrant",
  "vale",
  "virtualbox",
  "vscode",
  "yq"
]

ubuntu_packages = [
  "ack",
  "aha",
  "apt-file",
  "blueman",
  "build-essential",
  "composer",
  "crudini",
  "csvtool",
  "curl",
  "datamash",
  "db-util",
  "default-jre",
  "docker.io",
  "dosbox",
  "expect",
  "ffmpeg",
  "flameshot",
  "git",
  "git-extras",
  "gnome-sound-recorder",
  "gnumeric",
  "gnupg2",
  "gnuplot",
  "gpw",
  "graphviz",
  "graphviz-doc",
  "grepcidr",
  "gron",
  "htop",
  "hunspell-en-us",
  "hunspell-es",
  "hyphen-en-us",
  "hyphen-es",
  "iftop",
  "ipython3",
  "jo",
  "jq",
  "kitty"
]

todo = [
  "cobang",
  "cnijfilter2",
  "cnijfilter-common",
  "cnijfilter-mg2500series",
  "dbeaver-ce",
  "diff-so-fancy",
  "epson-inkjet-printer-escpr",
  "epson-printer-utility",
  "gcm",
  "google-chrome-stable",
  "gzdoom",
  "imagescan",
  "imagescan-plugin-gt-s650",
  "imagescan-plugin-networkscan",
  "imagescan-plugin-ocr-engine"
]
